title: PcapPlusPlus
email: pcapplusplus@gmail.com
description: A multiplatform C++ library for capturing, parsing and crafting of network packets. It is designed to be efficient, powerful and easy to use
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pcapplusplus.github.io"
twitter_username: seladb
github_username:  seladb
logo_source: /resources/logo_white.png
logo_width: 180

# Build settings
markdown: kramdown
remote_theme: seladb/just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Enable or disable the site search
search_enabled: true

# Enable or disable top navigation panel
top_navigation_enabled: true

# PcapPlusPlus specific variables
pcapplusplus_ver_num: 19.12
pcapplusplus_ver: v19.12
is_new_release: false

# Google Analytics Tracking Id
ga_tracking: UA-74037205-2

include:
  - _*_8h.html
  - _*_8h_source.html
  - _*_8h.js

exclude:
  - /api-docs/doxygen/
  - /api-docs/html/
  - README.md

